import "./globals.css";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import { poppins } from "./fonts";
import { cn } from "../lib/utils";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(poppins.className)}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
